Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name, email and UFID.
Please do not modify instruction cells or any cells with automated tests (marked with `[ASSERTS]`). Note: you can add new cells if you need them, but answers must be in the cells with `YOUR CODE HERE` or "YOUR ANSWER HERE" comments.

---

# Homework 0: Setting Up Your Environment!

## Preamble: Write your Name, Email and UFID

In [1]:
NAME = 'Hansika Weerasena'
EMAIL = 'hansikam.lokukat@ufl.edu'
UFID = 11639514

# YOUR CODE HERE
# raise NotImplementedError()

In [2]:
""" [ASSERTS] Check that your name, email, and UFID is filled in."""
assert NAME != '' and NAME != 'Your name here.' and len(NAME) > 3
assert EMAIL != '' and EMAIL != 'Your email here.' and len(EMAIL) > 7
assert type(UFID) == int and UFID != 12345678 and UFID >= 10000000 and UFID <= 99999999

## Academic Integrity

### <span style="color:red;">This is an individual assignment. Academic integrity violations (i.e., cheating, plagiarism) will be reported to SCCR!</span><br/>
#### The official CISE policy recommended for such offenses is a course grade of E. Additional sanctions may be imposed by SCCR such as marks on your permanent educational transcripts, dismissal or expulsion.
#### Reminder of the Honor Pledge: On all work submitted for credit by Students at the University of Florida, the following pledge is either required or implied: *"On my honor, I have neither given nor received unauthorized aid in doing this assignment."*

#### Acknowledgement: Do you acknowledge and understand the academic integrity warning above? 

In [3]:
academic_integrity_acknowledgement = True

# YOUR CODE HERE
# raise NotImplementedError()

In [4]:
""" [ASSERTS] Check that you acknowledge the academic integrity warning, you understanding it and have been reminded of the UF Honor Pledge."""
assert academic_integrity_acknowledgement

---
# [Task 1] Check that the cell below runs with no errors and that the version of Python is at least 3.8 and the version of Tensorflow is at least 2.1!

In [5]:
# Load packages we need
import sys
import os

import numpy as np
import scipy as sp
import pandas as pd

import sklearn

import matplotlib 

import tensorflow as tf

# Let's check our software versions
print('### Python version: ' + sys.version)
print('### Numpy version: ' + np.__version__)
print('### Scipy version: ' + sp.__version__)
print('### Pandas version: ' + pd.__version__)
print('### Scikit-learn version: ' + sklearn.__version__)
print('### Matplotlib version: ' + matplotlib.__version__)
print('### TensorFlow version: ' + tf.__version__)
print('------------')

/var/folders/z6/5n_s73l16t753clskkrk3n180000gq/T/ipykernel_24689/232635567.py:7: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
/Users/hansika/Documents/MLE/env/mle/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


### Python version: 3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]
### Numpy version: 1.26.3
### Scipy version: 1.12.0
### Pandas version: 2.2.0
### Scikit-learn version: 1.4.0
### Matplotlib version: 3.8.2
### TensorFlow version: 2.15.0
------------


### [Task 1] (15 Points) Paste in the cell below the output of the cell above (with the library versions)!

In [6]:
### Python version: 3.9.6 (default, Oct 18 2022, 12:41:40) [Clang 14.0.0 (clang-1400.0.29.202)]
### Numpy version: 1.26.3
### Scipy version: 1.11.4
### Pandas version: 2.1.4
### Scikit-learn version: 1.3.2
### Matplotlib version: 3.8.2
### TensorFlow version: 2.15.0

# YOUR CODE HERE
# raise NotImplementedError()

In [7]:
""" [ASSERTS] Check environment and versions."""
python_ver_split = sys.version.split('.')
assert int(python_ver_split[0]) >= 3 and int(python_ver_split[1]) >= 8
tf_ver_split = tf.__version__.split('.')
assert int(tf_ver_split[0]) >= 2 and int(tf_ver_split[1]) >= 1

---
# [Task 2] (10 Points) Tell us a little bit about yourself and what you hope to learn in this course

## [Task 2a] (5 Points) Write a brief description of your academic history (2-3 sentences is fine)

In [8]:
# I'm a fourth-year Ph.D. student in the Department of Computer & Information Science & Engineering at the University of Florida. 
# I received my BSc in Computer Science and Engineering from the University of Moratuwa, Sri Lanka where I graduated with a GPA of 3.94.
# My graduate research and research interets span a diverse range of topics, including cyber and hardware communication security, computer architecture, computer networks and security, and applied machine learning.


# YOUR CODE HERE
# raise NotImplementedError()

## [Task 2b] (5 Points) Briefly describe what you hope to learn in this course (a few sentences is fine)

In [9]:
# I would like to learn the key concepts in applied machine learning that will help me in my research. 
# Here, I hope to focus on the big picture of end-to-end pipeline development to address machine learning problems while also digging into mechanics of machine learning models.
# Furthermore, I'm very much interested in learning and getting hands on experince on fairly new machine learning concepts as autoencoders, transformers and diffusion models.

# YOUR CODE HERE
# raise NotImplementedError()

---
# [Task 3] (25 Points) Familiarize yourself with Python and NumPy and write some code to demonstrate your understanding. (Note: the basics notebook is a great resource!)

## [Task 3a] (5 Points) Create a numpy array 'a' that contains the integers 0 to 10. The shape of it should be (11,).

In [10]:
"""Put your code to create 'a' here.
"""

a = np.arange(11)

# YOUR CODE HERE
# raise NotImplementedError()

In [11]:
""" [ASSERTS] Check the answer."""
print(a) # this should print: "[ 0 1  2  3  4  5  6  7  8  9 10]"
assert a.shape == (11,)

[ 0  1  2  3  4  5  6  7  8  9 10]


## [Task 3b] (5 Points) Let 'b' be the numpy array where every element is the square of the corresponding element in 'a'. The shape should be (11,).

In [12]:
"""Put your code to create 'b' here.
"""

b = a**2

# YOUR CODE HERE
# raise NotImplementedError()

In [13]:
""" [ASSERTS] Check the answer."""
print(b) # this should print: "[  0   1   4   9  16  25  36  49  64  81 100]"
assert b.shape == (11,)

[  0   1   4   9  16  25  36  49  64  81 100]


## [Task 3c] (5 Points) Create an 3x4 numpy array 'c' of random integers in [-5, +5[ (use numpy.random.randint).

In [14]:
"""Put your code to create 'c' here.
"""

c = np.random.randint(-5, 5, size=(3, 4))

# YOUR CODE HERE
# raise NotImplementedError()

In [15]:
""" [ASSERTS] Check the answer."""
print(c)
assert c.shape == (3,4)

[[-4  4 -4  0]
 [ 4  0 -1  2]
 [ 0  2 -4 -1]]


## [Task 3d] (5 Points) Let 'd' be the reshaped version of 'c' as a 6x2 array.

In [16]:
"""Put your code to create 'd' here.
"""

d = c.reshape(6, 2)

# YOUR CODE HERE
# raise NotImplementedError()

In [17]:
""" [ASSERTS] Check the answer."""
print(d)
assert d.shape == (6,2)

[[-4  4]
 [-4  0]
 [ 4  0]
 [-1  2]
 [ 0  2]
 [-4 -1]]


## [Task 3e] (5 Points) Use numpy or scipy to draw 1000 i.i.d. random samples from the Gaussian distribution with the mean given by the first digit of your UFID and the standard deviation given by the square root of the sum of all digits in your UFID. For example, if you UFID is 2801104 the mean would be 2 and the standard deviation is 4. Let 'e' be the array with the random samples.

In [18]:
"""Put your code to create 'e' here.
"""

mean = 1
std_dev = np.sqrt(1 + 1 + 6 + 3 + 9 + 5 + 1 + 4)

e = np.random.normal(mean, std_dev, 1000)

# YOUR CODE HERE
# raise NotImplementedError()

In [19]:
""" [ASSERTS] Check the answer."""
assert e.shape == (1000,) or e.shape == (1000,1)